#!/bin/bash

TAGSFILE=~/tags.txt
FILETAGS=~/filetags.txt

file="$1"

fehpid=$(pgrep feh)
if [[ -n $fehpid ]]; then
  windowid=$(xdotool search  --pid $fehpid)
fi

touch $TAGSFILE

while true ; do
  added=$(cat "$TAGSFILE" | dmenu "${windowid:+-w $windowid}" -f -l 5 -p 'add tag > ')

  if [[ -z "$added" ]] ; then
    break;
  fi

  if ! grep -q "'^'${added}'$'" "$TAGSFILE"; then
    echo "New tag ${added}"
    printf '%s\n' "${added}" >> "$TAGSFILE"
  fi

  if ! grep -q "'^'${file},${added}'$'" "$TAGFILE"; then
    echo "Tagging ${file} as ${added}"
    printf '%s,%s\n' "$file" "$added" >> "$TAGFILE";
  fi
done
